// JS/Browser/React/src/App.js
import React, { Component } from 'react';
import './App.css';

// import { Stitch, 
//   AnonymousCredential,
//   RemoteMongoClient, 
//   BSON,
// } from "/Users/tkaye/Desktop/StitchSDKs/js/packages/browser/sdk/dist/cjs";

// import {
//   AwsServiceClient, 
//   AwsRequest
// } from "/Users/tkaye/Desktop/StitchSDKs/js/packages/browser/services/aws/dist/cjs";

import { Stitch, 
  AnonymousCredential,
  RemoteMongoClient, 
  // BSON,
} from 'mongodb-stitch-browser-sdk';

import {
  AwsServiceClient, 
  AwsRequest
} from 'mongodb-stitch-browser-services-aws';

class App extends Component {
  constructor(props) {
    super(props);
    this.state = { result: 'Blank' };
    this.login = this.login.bind(this);
    this.logout = this.logout.bind(this);
    this.callMongo = this.callMongo.bind(this);
    this.callAWS = this.callAWS.bind(this);
    this.callFunc = this.callFunc.bind(this);
    this.stitchClient = Stitch.initializeDefaultAppClient("stitchdocsexamples-pqwyr");
  }

  render() {
    return (
      <div className="App">
        <header className="App-header">
          <p>
            Edit <code>src/App.js</code> and save to reload.
          </p>
          <button className="button" onClick={this.login}> Login </button> <br></br>
          <button className="button" onClick={this.logout}> Logout </button> <br></br>
          <button className="button" onClick={this.callMongo}> Call Mongo Remote Find </button> <br></br>
          <button className="button" onClick={this.callAWS}> Call AWS S3 GetObject </button> <br></br>
          <button className="button" onClick={this.callFunc}> Call Stitch Function </button> <br></br>
          <p> { this.state.result } </p>
        </header>
      </div>
    );
  }

  setNewResult(res) {
    this.setState(state => ({
      result: res
    }));
  }

  login() {
    console.log("HI")
    this.stitchClient.auth.loginWithCredential(new AnonymousCredential()).then(user => {
      this.setNewResult(`Successfully logged in user with id: ${user.id}`);
    }).catch(err => {
      this.setNewResult(`Failed to login anonymous user with err: ${err}`);
    })
  }

  logout() {
    this.stitchClient.auth.logout().then(_ => {
      this.setNewResult(`Successfully logged out`);
    }).catch(err => {
      this.setNewResult(`Failed to logout with err: ${err}`);
    })
  }

  callMongo() {
    let mongoClient = this.stitchClient.getServiceClient(RemoteMongoClient.factory, "mongodb-atlas");
    mongoClient.db("store").collection("items").findOne().then(result => {
      this.setNewResult(`Successfully called mongo findOne(): ${JSON.stringify(result)}`); 
    }).catch(err => {
      this.setNewResult(`Failed to call mongo findOne() with error: ${err}`);
    })
  }

  callAWS() {
    let awsClient = this.stitchClient.getServiceClient(AwsServiceClient.factory, "myAWSService");

    const args = { Bucket: "tklivebucket",  Key: "example2" };

    const request = new AwsRequest.Builder().withService("s3").withAction("GetObject").withArgs(args);
    awsClient.execute(request.build()).then(res => {
      this.setNewResult(`AWS Result: ${JSON.stringify(res)}`);
    }).catch(err => {
      this.setNewResult(`AWS call failed with error: ${err}`);
    })
  }

  callFunc() {
    this.stitchClient.callFunction("getString", ["string1", "otherString2"]).then(result => {
      this.setNewResult(`Successfully called stitch function: ${result}`); 
    }).catch(err => {
      this.setNewResult(`Failed to call stitch function with error: ${err}`);
    })
  }
}

export default App;

// JS/Browser/Angular/src/app/app.component.ts
import { Component, OnInit } from '@angular/core';

import { Stitch, 
  AnonymousCredential,
  UserPasswordCredential,
  RemoteMongoClient, 
  BSON,
  StitchAppClient
} from "/Users/tkaye/Desktop/StitchSDKs/js/packages/browser/sdk/dist/cjs";

import {
  AwsServiceClient, 
  AwsRequest
} from "/Users/tkaye/Desktop/StitchSDKs/js/packages/browser/services/aws/dist/cjs";

// import { Stitch, 
//   AnonymousCredential,
//   UserPasswordCredential,
//   RemoteMongoClient, 
//   BSON,
//   StitchAppClient
// } from 'mongodb-stitch-browser-sdk';

// import {
//   AwsServiceClient, 
//   AwsRequest
// } from 'mongodb-stitch-browser-services-aws';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css'],
})
export class AppComponent implements OnInit {
  stitchClient: StitchAppClient;
  title = 'Sample';
  funcResult = "No Function Result";
  awsResult = "No AWS Result";
  mongoResult = "No Mongo Result";
  loginResult = "No Login Result";
  logoutResult = "No Logout Result";

  constructor() { }

  ngOnInit() {
    this.title = "MongoDB Stitch Sample App"

    const sampleDoc1 = '{ "int32": { "$numberInt": "10" } }';
    const ejs1 = BSON.EJSON.parse(sampleDoc1);
    console.log(ejs1)

    const sampleDoc2 = '{"AcceptRanges":"bytes","Body":{"$binary":{"base64":"aGVsbG8gdGhlcmU=","subType":"00"}},"ContentLength":{"$numberLong":"11"},"ContentType":"binary/octet-stream","LastModified":{"$date":{"$numberLong":"1551304351000"}},"Metadata":{}}';
    const ejs2 = BSON.EJSON.parse(sampleDoc2)
    console.log(ejs2)

    this.stitchClient = Stitch.initializeDefaultAppClient("stitchdocsexamples-pqwyr");
  }

  login() {
    this.stitchClient.auth.loginWithCredential(new AnonymousCredential()).then(user => {
      this.loginResult = `Successfully logged in user with id: ${user.id}`;
      this.logoutResult = "NA";
    }).catch(err => {
      this.loginResult = `Failed to login anonymous user with err: ${err}`
    })
  }

  logout() {
    this.stitchClient.auth.logout().then(_ => {
      this.logoutResult = `Successfully logged out`;
      this.loginResult = "NA";
    }).catch(err => {
      this.logoutResult = `Failed to logout with err: ${err}`
    })
  }

  callMongo() {
    let mongoClient = this.stitchClient.getServiceClient(RemoteMongoClient.factory, "mongodb-atlas");
    mongoClient.db("store").collection("items").findOne().then(result => {
      this.mongoResult = `Successfully called mongo findOne(): ${JSON.stringify(result)}`; 
    }).catch(err => {
      this.mongoResult = `Failed to call mongo findOne() with error: ${err}`;
    })
  }

  callAWS() {
    let awsClient = this.stitchClient.getServiceClient(AwsServiceClient.factory, "myAWSService");

    const args = { Bucket: "tklivebucket",  Key: "example2" };

    const request = new AwsRequest.Builder().withService("s3").withAction("GetObject").withArgs(args);
    awsClient.execute(request.build()).then(res => {
      this.awsResult = `AWS Result: ${JSON.stringify(res)}`;
    }).catch(err => {
      this.awsResult = `AWS call failed with error: ${err}`;
    })
  }

  callFunc() {
    this.stitchClient.callFunction("getString", ["string1", "otherString2"]).then(result => {
      this.funcResult = `Successfully called stitch function: ${result}`; 
    }).catch(err => {
      this.funcResult = `Failed to call stitch function with error: ${err}`;
    })
  }
}

<!--The content below is only a placeholder and can be replaced.-->
<div style="text-align:center">
  <h1>
    Welcome to {{ title }}!
  </h1>
  <img width="300" alt="Angular Logo" src="data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAyNTAgMjUwIj4KICAgIDxwYXRoIGZpbGw9IiNERDAwMzEiIGQ9Ik0xMjUgMzBMMzEuOSA2My4ybDE0LjIgMTIzLjFMMTI1IDIzMGw3OC45LTQzLjcgMTQuMi0xMjMuMXoiIC8+CiAgICA8cGF0aCBmaWxsPSIjQzMwMDJGIiBkPSJNMTI1IDMwdjIyLjItLjFWMjMwbDc4LjktNDMuNyAxNC4yLTEyMy4xTDEyNSAzMHoiIC8+CiAgICA8cGF0aCAgZmlsbD0iI0ZGRkZGRiIgZD0iTTEyNSA1Mi4xTDY2LjggMTgyLjZoMjEuN2wxMS43LTI5LjJoNDkuNGwxMS43IDI5LjJIMTgzTDEyNSA1Mi4xem0xNyA4My4zaC0zNGwxNy00MC45IDE3IDQwLjl6IiAvPgogIDwvc3ZnPg==">
</div>
<h2> Here are some basic Actions </h2>
<ul>
  <li>
    <span class="input-group-text" (click)="login()">Login: </span> {{loginResult}}
  </li>
  <li>
    <span class="input-group-text" (click)="logout()">Logout: </span> {{logoutResult}}
  </li>
  <li>
    <span class="input-group-text" (click)="callMongo()">Read From Mongo: </span> {{mongoResult}}
  </li>
  <li>
    <span class="input-group-text" (click)="callAWS()"> GetObject() from AWS </span> {{awsResult}}
  </li>
  <li>
    <span class="input-group-text" (click)="callFunc()">Call Stitch Function: </span> {{funcResult}}
  </li>
</ul>

<router-outlet></router-outlet>
